### ISSUE TITLE
Lib dem colour not recognised

### ISSUE THREAD

**Issue by gilesdring** [dringtech/ifg-charts#12]
I’m not sure if it’s that the staging site doesn’t have the most recent changes we made, but just wanted to flag that the legend doesn’t seem to recognise Liberal Democrats (example [here](https://ifg-staging.sbx.so/2-ministerial-roles?role=Parliamentary%20Under%20Secretary%20of%20State%20for%20Women%20and%20Equalities))

**Comment by gilesdring** [comment]
This was fixed in v0.7.0 - @scotteuser could you check if the site uses at least this version? There's likely to be a v0.8.0 shortly, so maybe wait for that!

**Comment by sachinsavur** [comment]
Happy for this to be marked as closed - thanks for fixing.
