### ISSUE TITLE
Tweak colour of 'persist' overlays and associated labels

### ISSUE THREAD

**Issue by philipnye** [dringtech/ifg-charts#16]
We hadn't spotted this previously - would you be able to tweak the colour of `persist` overlays ('First became MP' and 'Became peer' lines) and associated labels to #8D949A, please?

**Comment by gilesdring** [comment]
This is config injected into the library via the `overlay` property of the `ganttData` object. Would need to be overridden there.

**Comment by gilesdring** [comment]
Correction! I set a default for any overlay. I could change that... can I just check that this is for the colour of all overlays? Or are you asking for this to vary based on whether the overlay contains the "persist" flag? If the latter, I'd rather inject via config which would mean changing the options passed in via Drupal.

**Comment by gilesdring** [comment]
@graham73may Have updated code in the Drupal site for this and #7 - just pushed. FYI You might need to rebuild the library as well to incorporate some other fixes (I recently updated to 0.10.0) - my DDEV site is broken and it'll take too long to set up again!

**Comment by gilesdring** [comment]
This change in drupal site should resolve this.

https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/commit/d4d600793fe2659eeb2c4041c9724bbf5a903fd6

**Comment by philipnye** [comment]
@gilesdring Thanks. Unfortunately, in the process this seems to have changed the non-persist overlays and labels from dark grey (#333f48) to black. Would it be possible to rectify this, please?

cc @graham73may

**Comment by gilesdring** [comment]
Ah. Good spot. Should be overridden here:

https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/commit/d4d600793fe2659eeb2c4041c9724bbf5a903fd6#ae447a4da3afb25ad119086cbe22c34e7abb2267_103_103

Setting the desired colour for the unstyled lines to `#333f48`.

I will be able to do this tomorrow, unless @graham73may gets it sorted first.

**Comment by philipnye** [comment]
@gilesdring That would be great - thank you

**Comment by philipnye** [comment]
@gilesdring Just checking in on this issue - will you have any chance to address today? Thanks

**Comment by gilesdring** [comment]
I've made the very small change, but the branch I was working on no longer exists. 

The diff is as follows:

```
diff --git a/web/modules/custom/ifg_ministers/assets/js/ifg-ministers-initialise-chart.js b/web/modules/custom/ifg_ministers/assets/js/ifg-ministers-initialise-chart.js
index 95299e83..75fa74c0 100644
--- a/web/modules/custom/ifg_ministers/assets/js/ifg-ministers-initialise-chart.js
+++ b/web/modules/custom/ifg_ministers/assets/js/ifg-ministers-initialise-chart.js
@@ -100,7 +100,7 @@
                     endDate,
                     overlay: overlay.map(o => ({
                         // Colour different for persistent rows
-                        colour: o.persist === '1' ? '#8D949A' : undefined,
+                        colour: o.persist === '1' ? '#8D949A' : '#333f48',
                         // Then take all provided values - allows colour to be overriden
                         ...o,
                         // ...but persist needs to be true / false, not '1' / '0'
```

@graham73may What's the best way to submit this given the feature is now live? Do you want to create a patch branch and let me know so I can submit there?

**Comment by philipnye** [comment]
@gilesdring Thanks very much, Giles

@graham73may Would it be possible to incorporate this fix when you're handling the final SQL updates?

**Comment by graham73may** [comment]
Hi Both, 

Update deployed to staging alongside the SQL updates. 

@gilesdring, thanks for the git diff. Feel free to make a new branch / submit an MR if needed in the future if you prefer.

@philipnye Please review alongside the SQL updates and they'll go live together. 

Commit: https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/commit/04cc332f49185c1966c22addb5b8920f338e00db

**Comment by philipnye** [comment]
@gilesdring @graham73may Thanks very much, both
