### ISSUE TITLE
Legend centering

### ISSUE THREAD

**Issue by gilesdring** [dringtech/ifg-charts#3]
Centre the legend to the width of the plot.

Questions:

1. Is each line centred independently, or is the legend centred as a block
2. Does this affect the line breaks i.e. should an attempt be made to ensure each line of the legend is of a similar length / has a similar number of items

**Comment by gilesdring** [comment]
@philipnye Could you answer the questions above so I can let you know how involved this is as a task...

**Comment by gilesdring** [comment]
Basically, the layouts options are something like

<img width="1183" alt="image" src="https://github.com/dringtech/ifg-charts/assets/1731108/a2905bce-c602-417f-bd55-37c93cff9f0c">

In this image

* Options in the first row (a and c) are independency centred, whereas the second row options (b and d) are centred as a block
* Options in the first column (a and b) are wrapped to a maximum line length, wheras options in the second column (c and d) are cut such that the line length is equalised. 
* Note that options 'c' and 'd' are more complex scenarios, but render the tightest packing

**Comment by philipnye** [comment]
@gilesdring Incredibly helpful - we're literally just discussing this. Option A looks a good one to us. Thanks

**Comment by gilesdring** [comment]
OK - so simple wrapping to a maximum, centered per line. It may end up with a very short line (1 item) on the last line. Feels like a good first step.

**Comment by sachinsavur** [comment]
Looks great, thanks for your work on this Giles! Happy to close this one.
