### ISSUE TITLE
Excess whitespace where only one line of footer text

### ISSUE THREAD

**Issue by philipnye** [dringtech/ifg-charts#7]
Where there's only a single line of footer text there is too much whitespace between the bottom of the footer text/the CC logo and the bottom of the SVG. The amount of whitespace should be similar to the ammount between the top of the footer text/the CC logo and the blue bar (I think this is approx 11px in our static charts), with the footer section increasing in height with additional lines of text, following the logic of the header.

**Comment by gilesdring** [comment]
There was a minimum footer height, which I've altered the implementation of.

**Comment by gilesdring** [comment]
Not seeing this on the test version of the component.

![image](https://github.com/dringtech/ifg-charts/assets/1731108/2e88a55e-5cbc-46d4-a98f-dce98eb35513)

It may be that it's not in the version of the library on the site, or could be some CSS that's overriding the styling. Propose that it's re-tested when the next version has been released.

**Comment by philipnye** [comment]
@gilesdring Unfortunately we've tested on v0.9 and we're still seeing this. It looks to be the SVG element itself that's too tall rather than the `g` element containing the footer elements. Do you have any idea what selectors we might be talking about?

**Comment by graham73may** [comment]
Taking a look at the chart embedded into the page, the SVG element has some spacing at the bottom in the browser.

![image](https://github.com/user-attachments/assets/f36b4d24-8df9-45b8-8201-7cc57b680ba8)

I've exported as PNG:

![timeline](https://github.com/user-attachments/assets/4de51cdb-4783-4470-b8f7-1f72c9cf1f97)


And exported as SVG:

![timeline](https://github.com/user-attachments/assets/b2eaafe6-6d1c-4cf2-90bc-3b082dff23c0)

**Comment by graham73may** [comment]
Just taking a look at the elements inside the <svg> tag they seem to be the correct size (see lime green outline below), but the SVG element is taller than them.

![image](https://github.com/user-attachments/assets/5e36b285-2a19-476f-8054-1aa93e47dcd1)

It's like the viewBox has 20px too many, I can't see anything that may be causing it from our side (although I don't really know how the SVG is being drawn).

**Comment by gilesdring** [comment]
The problem is that there are actually two lines being sent to the component, the second one is an empty string. The code is calculating the footer height based on the length of the array. To fix this I could either strip out empty strings from the array, or they could be stripped out before injecting into the notes field of the component.

**Comment by graham73may** [comment]
Hi @gilesdring, any idea if this would this be something coming from Philip's SQL output? Or something from my side? 

Do you have an example of the problem string/data, it might help me track it down, thanks!

**Comment by gilesdring** [comment]
Hi @graham73may - the `notes` option is derived from this statement in the `web/modules/custom/ifg_ministers/assets/js/ifg-ministers-initialise-chart.js` code.

```js
                // 5. Use the ganttData to set up our chart.
                const {
                    data,
                    overlay,
                    startDate,
                    endDate,
                    title,
                    source,
                    notes,
                } = ganttData;
```

Looks like this `notes` is being concatenated to the `source` string as an array and passed in as the `notes` field to the chart.

```js
   notes: [source, notes],
```

Both these elements are set (as in `web/modules/custom/ifg_ministers/src/Form/MinistersPeopleWhoHeldRoleForm.php`) by a call like this:

```php
    $gant_metadata = $this->queryService->queryForGanttMeta($arguments);
```

I think this means that whatever the values of those strings, the array will have a length of two... A quick fix would be to filter in the `web/modules/custom/ifg_ministers/assets/js/ifg-ministers-initialise-chart.js`, something like:

```js
   notes: [source, notes].filter(x => x),
```

This would remove any empty values from the array, and the spacing would work OK.

**Comment by gilesdring** [comment]
@graham73may I'll make this change in the Drupal site... Will also put in a fix for #16 at the same time!

**Comment by gilesdring** [comment]
This change in drupal site should resolve this.

https://gitlab.com/sb-dev-team/instituteforgovernment.org.uk/-/commit/d4d600793fe2659eeb2c4041c9724bbf5a903fd6

**Comment by graham73may** [comment]
This is now deployed, spacing issue is resolved for me. Example png attached. 

![timeline (4)](https://github.com/user-attachments/assets/3a006fcb-0816-4e25-a51b-9da743112cd5)
