### ISSUE TITLE
Tweak contrast threshold

### ISSUE THREAD

**Issue by philipnye** [dringtech/ifg-charts#8]
- The labels on the blue (#00a8e1ff) ‘Minister of state’ bar and on the purple (#bd73d2ff) ‘Other parliamentary role’ bar (example below) are both dark grey, but are probably dark enough for the text to be white - could we tweak the contrast threshold please so that's the case?
- Using the same example, we think the purple is dark enough for the legend text to be the same colour, rather than being dark grey

I'll admit to losing track a little of how the controls for contrast colours worked - let us know if making these changes are within our control.

![timeline (5)](https://github.com/dringtech/ifg-charts/assets/5579544/f930663e-5fb7-409b-a661-25b0166ade1c)

**Comment by gilesdring** [comment]
This is in two parts, the first of which is relatively simple, and the second is a bit more complex...

I've added an additional property to the timeline component called `contrastClip`, which defaults to 165. Setting this clip lower will tend to make the text remain coloured as the contrast decreases. It was originally set to 250. You can now override this per chart, although bear in mind that setting this lower will make the charts less accessible.

The selection of white or grey as a contrast for overlays is a bit more involved. Basically, we can set the `contrastColour` for any category by editing the `categoryColours.js`. By default, these are set by finding the highest contrast between grey and white. I have overridden these for the MoS and Other Parl Role cases, but these are on a case by case basis. These are inherently less accessible than the default. Granted, this might be minimal.

**Comment by philipnye** [comment]
@gilesdring This sounds the right handling for these two things. When pushed to live we can double-check there aren't any unwanted consequences.

**Comment by sachinsavur** [comment]
Don't seem to be any unwanted consequences - happy for this to be marked as closed.
